# Generated by Django 4.1 on 2022-08-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Apellido(s)'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre(s)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Apellido(s)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre(s)'),
        ),
    ]
